### ISSUE TITLE
Add proper descriptions on various cards/sections

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/WildGuard#1]
#1
@anuragverma108 
Contents inside these sections are not proper . I want to modify it.

![image](https://github.com/user-attachments/assets/b83eceb5-140e-4a70-b381-c49f4c147fe0)

![image](https://github.com/user-attachments/assets/39e3412b-525a-4344-9c27-c442ac69308e)

**Comment by anuragverma108** [comment]
@PriyaGhosal Assigned!
