### ISSUE TITLE
Redesign the Footer

### ISSUE THREAD

**Issue by srinidhifd** [anuragverma108/WildGuard#10]
The footer section of the website needs a redesign for improved functionality and design.
 The following changes are necessary:

- Clickable Links: Ensure the "Terms of Use" and "Privacy & Policy" links navigate to the appropriate pages.
- Social Media Icons: Add icons for relevant social media platforms (e.g., Facebook, Twitter, Instagram, LinkedIn) with links directing users to the organization's respective social media pages.
- Improved Formatting: Check the alignment and spacing of the text, links, and newly added icons to ensure a more polished and visually appealing design.
- Dynamic Copyright Year: Ensure the copyright text updates automatically to reflect the current year.

![footer](https://github.com/user-attachments/assets/b5f4b7ee-f78e-4b81-ac8e-9e3d1ac67c35)

@anuragverma108 Please assign this issue under hacktoberfest label.
Thank you

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
