### ISSUE TITLE
Feature Request: Add "Read More" Section for "Tree Plantation"

### ISSUE THREAD

**Issue by Sumit1911** [anuragverma108/WildGuard#104]
I would like to propose adding a "Read More" section for the "Tree Plantation" section. This new feature will provide visitors with detailed information about the benefits and importance of tree plantation, ongoing efforts, and how users can contribute. The goal is to enhance user engagement by offering an expanded view of the topic.

Implementation:
*Add a "Read More" link/button to expand or redirect to a page with additional content.
*Ensure consistency with the website’s design and responsiveness across devices
![Screenshot 2024-10-01 212115](https://github.com/user-attachments/assets/01fbdeec-6915-4a7a-ac08-8a7b2f18c5cb)

Would you please assign me this task under the Hacktoberfest 2024 tag

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
