### ISSUE TITLE
Adding a Carousel to the image gallery above the footer in the website.

### ISSUE THREAD

**Issue by PankajR007** [anuragverma108/WildGuard#11]
Adding the Carousel to enhance the UI.
Attached the image gallery which i'm enhancing as a carousel. Making it better at user experience.
![image](https://github.com/user-attachments/assets/38cff1f7-9537-4e68-aacc-2b174b418a9b)

@anuragverma108  Please assign this issue under hacktoberfest label.
Thank you

**Comment by anuragverma108** [comment]
@PankajR007 
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
