### ISSUE TITLE
Refactor style tag into separate css file

### ISSUE THREAD

**Issue by clydehenry3** [anuragverma108/WildGuard#111]
Hello there @anuragverma108! I would like to refactor the style tag in the html to its own separate css file within the project.

**Comment by clydehenry3** [comment]
Please disregard

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by PushkarDesai-06** [comment]
### Hey, can you please assign this issue to me?
 #### Thank You
