### ISSUE TITLE
Certain UI changes

### ISSUE THREAD

**Issue by nishakp3005** [anuragverma108/WildGuard#113]
1. Navigation bar should have a semi-opaque background for more visibility. 
2. The sections should be highlighted on the nav bar on visiting.
3. Search bar should be more clearly visible / Use a different icon for search bar.
4. Under about section the section-text should be left-aligned for more readability.
I would like to make these changes!
@PriyaGhosal

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
