### ISSUE TITLE
Add a Scroll down progress bar matched to the website design theme

### ISSUE THREAD

**Issue by MastanSayyad** [anuragverma108/WildGuard#1138]
Hi @anuragverma108 

I would like to add a scroll down progress bar on the top of the website which helps users to navigate in long pages to know how much longer the page is yet to be scroll and to track at what point of the website they are present 

![image](https://github.com/user-attachments/assets/b527d48e-ca4a-4b77-ab80-cabc6504747d)

**For example like this:**

![image](https://github.com/user-attachments/assets/86982b6e-b295-4201-85aa-eb9db880b2fc)

Could you please assign this issue to me under Hacktoberfest?

**Comment by anuragverma108** [comment]
You can start working @MastanSayyad

**Comment by Parth04exe** [comment]
@anuragverma108 please review my pull request
