### ISSUE TITLE
Enhance Contact Form: Split Name Fields, Add Icons, Improve Placeholders, and Update CSS

### ISSUE THREAD

**Issue by ArisuAbhilash** [anuragverma108/WildGuard#119]
Issue Description:
Objective: Enhance the user experience of the contact form by implementing the following changes:

1. Split Name Field:
 Divide the current "Your Name" input field into two separate fields: "First Name" and "Last Name."
 Ensure that both fields are required and validate the inputs accordingly.

2.Add Icons:
 Integrate icons into the input fields for better visual representation. Icons can be added using CSS background images or an icon 
 library such as Font Awesome.
 Ensure the icons are appropriately sized and positioned within the input fields.

 3.Improve Placeholders:
  Update the placeholders for all input fields to be more descriptive and user-friendly.

  Example placeholders:
  For "First Name": "Enter your first name (e.g., John)"
  For "Last Name": "Enter your last name (e.g., Doe)"
  For "Your Message": "Type your message here..."
  Update Background Color:

 4.Enhance the overall aesthetics of the contact form by updating the background color to a softer shade or gradient that aligns with 
 the site's theme.
  Consider using a subtle contrast to make the form stand out.

5.Enhance CSS:

 Review and update the CSS styles to improve the visual layout and spacing of the form elements.
 Ensure that the form is fully responsive and looks good on various screen sizes.
 
6.Additional Notes:

Ensure that the form retains its validation features for the new fields.
Test the form after implementation to verify functionality and user experience.
Consider making CSS adjustments to accommodate the added icons and new field structure.

**Comment by ArisuAbhilash** [comment]
kindly assign this task to @ArisuAbhilash

**Comment by ArisuAbhilash** [comment]
@anuragverma108 please assign me this task

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by ArisuAbhilash** [comment]
@PriyaGhosal thanks for assigning me this task i am working on it
![Screenshot 2024-10-04 013304](https://github.com/user-attachments/assets/5b0a7986-a2fe-45ca-9ff6-75d4e54702ef)
![Screenshot 2024-10-04 020108](https://github.com/user-attachments/assets/e412425a-78b9-4d53-8caf-d75d08d52753)

**Comment by ArisuAbhilash** [comment]
hi i am closing this issue because i provided the solution and also send pr request
