### ISSUE TITLE
Adding a Language Translation Feature

### ISSUE THREAD

**Issue by PankajR007** [anuragverma108/WildGuard#12]
From the DropDown if a different language is selected the page must be Translated in that particular selected to language. 

![Screenshot (64)](https://github.com/user-attachments/assets/3e2f2ba9-228a-4c14-8897-9f9c21431d8b)

@anuragverma108 Please assign this issue under hacktoberfest label.
Thank you

**Comment by maniranjan2023** [comment]
@anuragverma108 sir, please assign this issue under hacktoberfest label .....i want to contribute and resolve this issue....

**Comment by anuragverma108** [comment]
@PankajR007 
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by anuragverma108** [comment]
@maniranjan2023 
Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
