### ISSUE TITLE
Create SaveOcean.html page for read more

### ISSUE THREAD

**Issue by kavya-r30** [anuragverma108/WildGuard#120]
My name is Kavya, and I would like to create a new clearOcean.html file for the "Read More" anchor provided in the "Clear Ocean" div. I plan to include relevant information that supports your website's mission and ensures the content aligns with the design of the index page, making it user-friendly and cohesive. 

Would you please assign me this task under the Hacktoberfest 2024 tag

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
