### ISSUE TITLE
Adding hover effects and changing texts for our mission, our vision, next plan

### ISSUE THREAD

**Issue by shobhit15082003** [anuragverma108/WildGuard#121]
![Screenshot 2024-10-01 232626](https://github.com/user-attachments/assets/ddbb8920-4b65-4b18-a6fb-7cf37c6f3485)
![Screenshot 2024-10-01 232739](https://github.com/user-attachments/assets/a9d9c163-8558-410e-ae75-af28d670094b)
![Screenshot 2024-10-01 232752](https://github.com/user-attachments/assets/42e8656a-47a7-433e-aade-97fad083d6ff)

These are the changes I am planning to make if there is anything else please let me know.

@anuragverma108 please assign me this issue and also mark as hacktoberfest.

**Comment by adilkadivala** [comment]
hey @anuragverma108 let assign me this issue ..

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
