### ISSUE TITLE
Adding progress bar on the top of the page.

### ISSUE THREAD

**Issue by harshit69x** [anuragverma108/WildGuard#125]
As we scroll down the page the progress bar will increase. It will give a good look to the page.

**Comment by harshit69x** [comment]
please assign me this issue

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
