### ISSUE TITLE
feat: implement prettier setting in entire project #19

### ISSUE THREAD

**Issue by realvishalrana** [anuragverma108/WildGuard#131]
use case for Prettier is to automatically format code consistently across a project, ensuring a unified code style and improving readability without requiring manual formatting adjustments by developers.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by realvishalrana** [comment]
@PriyaGhosal review and merge https://github.com/anuragverma108/WildGuard/pull/389
