### ISSUE TITLE
Dark Mode Implementation

### ISSUE THREAD

**Issue by AyushiChopra02** [anuragverma108/WildGuard#133]
the application currently lacks a dark mode feature, which can enhance user experience, especially in low-light environments.

To implement this, we can introduce a toggle button that adds a specific class to the body element, switching between light and dark themes. This will involve defining a separate set of CSS variables for dark mode colors, which will allow us to easily adjust the styling across different components.

Please assign this issue to me for Hacktoberfest 2024. Implementing this feature will provide users with greater flexibility and improve accessibility.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
