### ISSUE TITLE
Visually Appealing Background with CSS Shapes and Animations

### ISSUE THREAD

**Issue by AyushiChopra02** [anuragverma108/WildGuard#134]
The application currently lacks a visually engaging background that can enhance the overall aesthetic and user experience. By utilizing CSS shapes and animations, we can create a dynamic and appealing background that will capture users' attention and make the interface more interactive.

To implement this, we can design various shapes (like circles, squares, and polygons) and animate them using CSS animations or keyframes. This will not only provide a unique look but also maintain fast loading times compared to static images.

Please assign this issue to me for Hacktoberfest 2024. Implementing this feature will elevate the visual appeal of the application and provide a more immersive experience for users.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
