### ISSUE TITLE
Style the Scrollbar to Match the Overall Theme

### ISSUE THREAD

**Issue by AyushiChopra02** [anuragverma108/WildGuard#135]
The application currently features a default scrollbar that does not align with the overall aesthetic and theme of the website. Customizing the scrollbar can significantly enhance the user experience and provide a cohesive look across all components.

To implement this, we can use CSS to style the scrollbar, adjusting its width, color, and background to match the website's theme. This will involve using the ::-webkit-scrollbar pseudo-element for WebKit browsers and ensuring compatibility with other browsers through appropriate fallbacks.

Please assign this issue to me for Hacktoberfest 2024. Implementing this feature will improve the visual consistency of the application and create a more polished user interface.

**Comment by Varchasavkr** [comment]
@anuragverma108 !!
Hello anurag ,
I want to fix this issue #135 and make website more appealing 
Kindly Assign this to me under HacktoberFest2024
Thankyou

**Comment by AyushiChopra02** [comment]
@anuragverma108 
I want to work on issue #135 as I have raised this issue.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
