### ISSUE TITLE
Enhance the Search Bar with Auto-Suggestions

### ISSUE THREAD

**Issue by AyushiChopra02** [anuragverma108/WildGuard#136]
The current search bar lacks features that could greatly enhance user experience, such as auto-suggestions or a dropdown displaying recent searches and popular queries. Implementing these features will make it easier for users to find what they are looking for and improve overall interaction with the application.

To implement this, we can utilize JavaScript to listen for input events in the search bar and fetch relevant suggestions based on user input. This can include displaying recent searches stored in local storage or querying an API for popular searches. The dropdown can be styled to match the website's theme, ensuring a seamless integration into the existing design.

Please assign this issue to me for Hacktoberfest 2024. Enhancing the search functionality will significantly improve usability and make the application more user-friendly.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
