### ISSUE TITLE
Provide Visual Feedback for Form Submissions

### ISSUE THREAD

**Issue by AyushiChopra02** [anuragverma108/WildGuard#137]
The current application does not provide adequate visual feedback upon form submissions, such as when users submit the search form. Implementing feedback mechanisms like toast notifications or modals will inform users of successful submissions or any errors that may have occurred.

To achieve this, we can create a function that triggers a toast notification or modal once a form is submitted. This could include messages such as “Submission Successful!” or “Error: Please try again.” The notifications can be styled to match the overall theme of the application, ensuring a cohesive user experience.

Please assign this issue to me for Hacktoberfest 2024. Adding visual feedback will enhance user engagement and improve the overall usability of the application.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
