### ISSUE TITLE
Bottom to Top Button visibility (z-index) and radius issue

### ISSUE THREAD

**Issue by adilkadivala** [anuragverma108/WildGuard#139]
Bottom to top Button is hide inside insta-post section,  so it should be top of this section, 

https://github.com/user-attachments/assets/700b69fc-d4db-4bbb-8bef-2c51b18e0aad

and button should be propper round shaaped,  now it is like ovel shaped ..

![radius issue](https://github.com/user-attachments/assets/1620c530-d8cb-475d-b6d1-87897284c714)

**Comment by adilkadivala** [comment]
hey @piyushshrma  let assign it me,,

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
