### ISSUE TITLE
The "y" in "New york" is incorrectly lowercase. The original description lacks proper punctuation and flow. 

### ISSUE THREAD

**Issue by Shashankk99** [anuragverma108/WildGuard#1396]
Hello @anuragverma108, 

In the Animal Shelter Fundraiser section, the "y" in "New york" is incorrectly lowercase. The original description lacks proper punctuation and flow.

![378125817-9f11c11d-51cc-4132-8577-26bfa1078f9a (1)](https://github.com/user-attachments/assets/6a6fbebc-5c12-45a4-b2e6-ead79e266dd0)

Kindly assign it to me.

Thank you!

**Comment by wrexrus** [comment]
![image](https://github.com/user-attachments/assets/de579297-a8bb-4134-9e45-54532e9ad208)
this has corrected already check and kindly close this issue
