### ISSUE TITLE
Adding functionality to "Learn More Us" button in about section and at the bottom of the page.

### ISSUE THREAD

**Issue by pallavkishor** [anuragverma108/WildGuard#14]
ISSUE
There are two "Learn More Us" buttons, one in About section and other at the bottom of the page. But on click of these buttons nothing happens. 
SOLUTION:
I want to add functionality to these buttons and on click the user should get to know more details about the website.

https://github.com/user-attachments/assets/a7541645-2829-486c-8e8f-dd824e71c6cf

@anuragverma108  Please assign me this issue under hacktoberfest label.

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  

Happy open-source contributing! 🚀
