### ISSUE TITLE
#141   Read More should have a hover effect and English lang button also

### ISSUE THREAD

**Issue by Varchasavkr** [anuragverma108/WildGuard#141]
https://github.com/user-attachments/assets/50f98c84-23e0-4a23-95ec-95bcfa123258

In this there should be a hover effect on English Language and Read More button will look much better with an hover effect with smooth transition !

@anuragverma108 I have fixed this issue #141  using :hover and :focus 
and created a PR 
Kindly merge this under Hacktoberfest 2024 accepted 

Thankyou

**Comment by Varchasavkr** [comment]
My PR  number is #142 

Thankyou

**Comment by shbhmexe** [comment]
hey assign me this issue ,, i want to solve this and have potential skils to solve this

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
