### ISSUE TITLE
#144 Language Options Not Accessible on Header

### ISSUE THREAD

**Issue by GodMischief** [anuragverma108/WildGuard#144]
https://github.com/user-attachments/assets/5b44d1f7-64f8-4d2e-a99e-8e0a512c2834

The website's header currently displays three language options, but the site content is only showing in English. The language selection feature is not functional.

Proposed Solution: I can implement the necessary functionality to make the language options accessible and ensure that the page content can be viewed in all available languages. This will enhance the user experience and provide a seamless multilingual interface.

Please assign this issue to me under the Hacktoberfest topic so I can work on it. Thank you!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
