### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by Mandipthakur** [anuragverma108/WildGuard#145]
As this website have Service and Donation page, there might be need for Frequently Asked Question section for visitors to learn about the website more efficiently. 
Please assign this to me.

**Comment by kartikey369-ind** [comment]
its done by me

**Comment by Munazir151** [comment]
assign me this issue under hacktoberfest 2024

**Comment by Munazir151** [comment]
What are the questions to be added

> @Mandipthakur Thanks for creating the issue in WildGuard! The issue has been assigned to you.
> 
> Before you start working on your PR, please make sure to:
> 
> * ⭐ Star the repository if you haven't already.
> * Pull the latest changes to avoid any merge conflicts.
> * Attach before & after screenshots in your PR for clarity.
> * Include the issue number in your PR description for better tracking.
> 
> Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator – for more updates!
> 
> We're excited to see your contribution as part of Hacktoberfest 2024! 🎉 Happy open-source contributing!


What are the questions to be added in the faq.
provide the question and relevant answers.

**Comment by Mandipthakur** [comment]
@PriyaGhosal @anuragverma108  I have added PR for my issue no  145 here at #285 . I have added Screenshot aswell.  Please review and accept the PR.
