### ISSUE TITLE
Add a Hover Effect to "Become a Partner" Button for Theme Compatibility

### ISSUE THREAD

**Issue by Mayukh69-gif** [anuragverma108/WildGuard#1454]
The "Become a Partner" button currently lacks a hover effect that complements the overall website theme. To improve user experience and visual consistency, I propose changing the hover effect to something that aligns with the site's design aesthetics.

**Comment by PAVAN507-STAR** [comment]
Hii @Mayukh69-gif I would like to work on this issue.Can u please assign this issue to em

**Comment by Mayukh69-gif** [comment]
hi @PAVAN507-STAR, I have already worked on this issue, if u want to work on this issue again create a new issue, please or contact @anuragverma108

**Comment by PAVAN507-STAR** [comment]
@Mayukh69-gif If its not yet solved i would like to work on it

**Comment by Mayukh69-gif** [comment]
@PAVAN507-STAR I already solved this issue.
