### ISSUE TITLE
Fix Scroll To Top Button UI and Footer Alignment

### ISSUE THREAD

**Issue by diwakarshukla941** [anuragverma108/WildGuard#146]
There are layout and positioning issues with the "Scroll to Top" button and footer on the webpage. The button overlaps with content, and the footer is misaligned on different screen sizes.

Tasks to be Done:

Fix the UI and positioning of the "Scroll to Top" button.
Adjust the footer positioning and alignment to ensure it displays correctly across different screen sizes.
Steps:

Correct the CSS of the button to ensure it remains fixed at the bottom-right of the viewport and is visible only when scrolling.
Ensure the footer is properly aligned and responsive, maintaining consistent spacing and no overlap with content.
Proposed Fix: I will work on fixing the "Scroll to Top" button UI and properly position the footer to improve the layout and responsiveness.

Expected Outcome: After the fix, the "Scroll to Top" button will be properly positioned and user-friendly, and the footer will remain aligned and responsive across all screen sizes.

**Comment by anuragverma108** [comment]
@diwakarshukla941 Thanks for creating the issue in *WildGuard*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by anuragverma108** [comment]
@harshendram Please don't start working on issue without it is being assigned.

**Comment by anuragverma108** [comment]
@diwakarshukla941 Start Working!
