### ISSUE TITLE
Contact us Page

### ISSUE THREAD

**Issue by abhipariharr** [anuragverma108/WildGuard#147]
![Screenshot 2024-10-02 102537](https://github.com/user-attachments/assets/711d14d5-cdd5-48ae-b935-aa22555ca3ed)

i can make the contact us page more attractive.

**Comment by Munazir151** [comment]
assign me this issue under hacktoberfest 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
