### ISSUE TITLE
Testimonies section

### ISSUE THREAD

**Issue by HrdxH** [anuragverma108/WildGuard#15]
![Screenshot 2024-09-29 174357](https://github.com/user-attachments/assets/a634c149-59f2-46a2-a479-61fadae8cf6f)
 I want to edit this section to add a click function so that the testimonies change and also change the text to make it appropriate.

Please assign me this issue under hacktoberfest 2024

**Comment by HrdxH** [comment]
@anuragverma108 Kindly assign me this issue

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  

Happy open-source contributing! 🚀
