### ISSUE TITLE
[Bug] Leaf logo appears distorted and unclear due to imperfect rounding

### ISSUE THREAD

**Issue by megh-bari** [anuragverma108/WildGuard#155]
**Issue Description:**
The logo currently appears with imperfect rounding, making it look uneven. Additionally, the logo is rendering behind other elements on the page, which affects its visibility.

**Expected Behavior:**
The logo should have a perfectly rounded appearance.
The logo should always stay in front of other page elements to ensure it's clearly visible.

**Suggested Fix:**
Ensure proper CSS styling to create a perfectly rounded logo.
Adjust the z-index or other positioning properties to keep the logo in the foreground. 

![image](https://github.com/user-attachments/assets/8cb39b99-e13a-48b5-9802-950a70736dd2)

Hello @anuragverma108 

Could you please assign the "Hacktoberfest" label to this issue? I’d love to work on it as part of Hacktoberfest.

Thank you!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
