### ISSUE TITLE
Adding functionality to "Terms of use" and "Privacy & Policy" Page at the bottom of the page.

### ISSUE THREAD

**Issue by realvishalrana** [anuragverma108/WildGuard#16]
![image](https://github.com/user-attachments/assets/00abaecc-3a68-45a7-8d26-f66d7003a2d2)

**Comment by realvishalrana** [comment]
I would like to contribute in your website . I want to Adding functionality to "Terms of use" and "Privacy & Policy"

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  

Happy open-source contributing! 🚀
