### ISSUE TITLE
Add Various Profiles and update the footer .

### ISSUE THREAD

**Issue by Sthorat22** [anuragverma108/WildGuard#163]
![image](https://github.com/user-attachments/assets/57c010fe-25e1-4879-af57-4ff4bf26e80b)

Hacktoberfest2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by Sthorat22** [comment]
As this has already addedin footer will close this issue.
![image](https://github.com/user-attachments/assets/99edaaeb-b30f-4448-94b5-bb8ebf2619db)
