### ISSUE TITLE
Structural Enhancements and Styling Updates for Footer

### ISSUE THREAD

**Issue by mitgajera** [anuragverma108/WildGuard#164]
![Screenshot 2024-10-02 143918](https://github.com/user-attachments/assets/f83d9909-96ac-4afd-8748-db9ab7cc2667)

Hi @anuragverma108 

This PR introduces structural improvements and styling updates to the footer section. Key changes include:
- Structural Enhancements:
Adjusted the layout of the footer links ("Terms of Use" and "Privacy & Policy") for better alignment and spacing.
Ensured the footer structure is cleaner and more organized to improve readability and flow.

- Styling Updates:
Modified the color scheme to enhance contrast between the text and background.
Updated padding and margin for more balanced spacing, improving the overall aesthetic and symmetry.
These changes ensure the footer appears cleaner and more aligned with modern design standards, without altering its functionality.

Please assign this issue to me under Hacktoberfest2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
