### ISSUE TITLE
Improve Hover Effect on "View Events" Button

### ISSUE THREAD

**Issue by kaiyumdev** [anuragverma108/WildGuard#167]
Currently, the hover effect on the "View Events" button does not provide a clear or visually appealing change. I would like to enhance the hover state by updating the color to improve user interaction and make the button more engaging.

Could you please assign me this issue? I would be happy to work on it.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
