### ISSUE TITLE
Missing hover effect on a specific button

### ISSUE THREAD

**Issue by tausif-fardin** [anuragverma108/WildGuard#168]
Currently, all buttons across the application follow a consistent hover effect, except for this particular button. For the sake of uniformity and a better user experience, I believe this button should have a similar hover effect.

Proposed Solution:
I would like to implement the missing hover effect on this button to ensure consistency. If this is a valid issue, please assign it to me, and I'll be happy to work on it.

![image](https://github.com/user-attachments/assets/2d807b5c-4943-4b2d-93f9-0375075986e4)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
