### ISSUE TITLE
Contact us revamp

### ISSUE THREAD

**Issue by kevicebryan** [anuragverma108/WildGuard#169]
I'd like to revamp the contact us page to make it better and fit the current design:
![Screenshot 2024-10-02 at 17 01 25](https://github.com/user-attachments/assets/11b763b8-1065-4050-8b07-6578afc022e8)

something like this,:
![image](https://github.com/user-attachments/assets/9525e18b-ff6c-4fd2-b602-82363468c3d2)

**Comment by kevicebryan** [comment]
if this issue isn't yet assigned to anyone, I'd be glad to be an assignee

**Comment by PriyaGhosal** [comment]
@kevicebryan Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
