### ISSUE TITLE
Our Vision and Next Plan button is not working

### ISSUE THREAD

**Issue by realvishalrana** [anuragverma108/WildGuard#17]
![image](https://github.com/user-attachments/assets/631fad53-771c-4e69-8934-6564d9c923f4)

@anuragverma108 
Our Vision and Next Plan button is not working proper. I want to modify it. Please assign the issue under hacktoberfest

**Comment by maniranjan2023** [comment]
@anuragverma108 sir, i want to make three non working button that is our mission, our vision and next plan button working....please assign this issue to me.....

**Comment by realvishalrana** [comment]
@anuragverma108 Please review and merge https://github.com/anuragverma108/WildGuard/pull/130
