### ISSUE TITLE
Dropdown button outline missing on click & design improvement suggestion

### ISSUE THREAD

**Issue by tausif-fardin** [anuragverma108/WildGuard#171]
When clicking the dropdown button to change the language, the button outline disappears, which may affect the visual feedback for users. Additionally, the dropdown options currently display the default style, and I believe there's an opportunity to enhance the design for a more polished look.

![image](https://github.com/user-attachments/assets/8ac2b41a-2092-49cf-8fb7-0c94a98522c9)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
