### ISSUE TITLE
Add Footer to terms of use and privacy page and beautify it.

### ISSUE THREAD

**Issue by Sthorat22** [anuragverma108/WildGuard#173]
![image](https://github.com/user-attachments/assets/df742158-3875-46a5-91c5-3409f43c14a6)
![image](https://github.com/user-attachments/assets/2db9370d-1155-45c9-bec8-edbd010ddfbc)
HacktoberFest 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
