### ISSUE TITLE
Add Back Button From Become Partner Page 

### ISSUE THREAD

**Issue by Sthorat22** [anuragverma108/WildGuard#176]
![image](https://github.com/user-attachments/assets/dd47a5c9-0906-4eac-b3f0-4689b9b87dbc)

Hacktoberfest2024

**Comment by Abhinayadanda** [comment]
please assign me this for Hacktoberfest2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
