### ISSUE TITLE
Create a Dedicated "Tree Plantation" Page

### ISSUE THREAD

**Issue by Mudassir97** [anuragverma108/WildGuard#179]
The current "Tree Plantation" section within the repository appears to be incomplete or lacking clear functionality. To enhance user experience and provide more comprehensive information, it is recommended to create a separate, dedicated page specifically for tree plantation initiatives.
This dedicated page could include the following elements:
Overview, Projects, Impact, Get Involved,

Kindly assigned me this issue under Hacktoberfest 2024

**Comment by Abhinayadanda** [comment]
can you please assign me this issue, i would like to contribute to Hacktoberfest 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
