### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by Madan2468** [anuragverma108/WildGuard#18]
I would add links in your footer section like - social accounts , GitHub and make it visual appealing with icons. Attaching the example of footer for above reference.
<img width="1253" alt="Screenshot 2024-09-29 at 11 07 03 PM" src="https://github.com/user-attachments/assets/bfd98596-6905-492c-bce4-c4e8a3e4c097">

**Comment by Madan2468** [comment]
@anuragverma108 take a look and lemme know

**Comment by anuragverma108** [comment]
@Madan2468 

Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  

Happy open-source contributing! 🚀
