### ISSUE TITLE
Clear the clutter and extra elements in Why choose us section

### ISSUE THREAD

**Issue by Insaneuchiha** [anuragverma108/WildGuard#184]
Buttons are misaligned and same thing is repeated twice why choose us section 
![image](https://github.com/user-attachments/assets/d375a30f-2325-4af4-9904-2a584535414b)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
