### ISSUE TITLE
Add Hindi Language Support to the Website

### ISSUE THREAD

**Issue by Tembhare-shikha25** [anuragverma108/WildGuard#191]
Hello @anuragverma108 

The website currently supports only English,French and spanish, and we would like to expand its accessibility by adding support for the Hindi language. This will allow Hindi-speaking users to navigate and interact with the website in their native language, improving the overall user experience for this audience. Hindi is spoken by a large population globally, and incorporating it into the website will help us reach a wider audience and make the content more inclusive.

Kindly assign me this issue under Hacktoberfest 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
