### ISSUE TITLE
[BUG]:Footer word used more than once

### ISSUE THREAD

**Issue by Varchasavkr** [anuragverma108/WildGuard#192]
https://github.com/user-attachments/assets/32d6a2e1-a652-4b48-b0d9-09a49635bfa6

#Hacktoberfest2024

Kindly merge the fix corresponding to this issue
Thankyou

**Comment by Varchasavkr** [comment]
> can you please assign me this

Already solve by me in PR #187
@anuragverma108 Kindly review code and merge pull request
#hacktoberfest2024

**Comment by PriyaGhosal** [comment]
@Varchasavkr Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
