### ISSUE TITLE
Remove Terms of use and Privacy & Policy in footer

### ISSUE THREAD

**Issue by kanduru-abhiram** [anuragverma108/WildGuard#198]
Hello @anuragverma108,

Terms of use and Privacy & Policy are kept twice and not required to be added in same container. May be you can add the logo of the website and tagline in that place.

Kindly assign me this issue under Hacktoberfest 2024.
![image](https://github.com/user-attachments/assets/dcafb722-007f-4c89-94c8-0b57a6ae3b8a)

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
