### ISSUE TITLE
Add a Separate Copyright Policy Page

### ISSUE THREAD

**Issue by PriyaGhosal** [anuragverma108/WildGuard#2]
Hello @anuragverma108 ,

To comply with legal standards and protect the intellectual property rights associated with the content on Skill Wise, I propose the addition of a dedicated Copyright Policy page. This page should outline the platform's policies on copyright infringement, guidelines for content usage, and procedures for reporting violations. This will ensure transparency for users and contributors, reinforcing the platform’s commitment to respecting and safeguarding creators' rights.

Kindly assign me this issue under Hacktoberfest 2024

**Comment by anuragverma108** [comment]
Assigned!
