### ISSUE TITLE
Add smooth fade up animation while scrolling 

### ISSUE THREAD

**Issue by 21prnv** [anuragverma108/WildGuard#200]
Hi @anuragverma108 , I wanted to add a fading animation while scrolling on the website to make it more beautiful and attractive. Please assign me this issue with the Hacktoberfest label.

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
