### ISSUE TITLE
Align the content to center 

### ISSUE THREAD

**Issue by 21prnv** [anuragverma108/WildGuard#203]
Hi @anuragverma108  could you please assign me this issue with hactoberfest label? I will align everything in place for a better user interface
![image](https://github.com/user-attachments/assets/0cab5258-199c-4ba0-8d99-a23f040e45f7)
![image](https://github.com/user-attachments/assets/f72b1f75-1582-4f03-abd8-a06a49c8dcaf)

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label
