### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by SaumyaSubham** [anuragverma108/WildGuard#204]
Hello @anuragverma108 
I'm a newbie contributor, and I saw become a partner is not in the readme.md file. I'm here to update the necessary elements such like Become a Partner etc. to provide a new look of readme.md file of the WildGuard. I propose the addition of new readme.md file gives an outstanding dedication to the contributors for contributing this repo or project.

Kindly assign me this issue under Hacktoberfest 2024

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
