### ISSUE TITLE
Navigate to profile link after clicking on it.

### ISSUE THREAD

**Issue by 21prnv** [anuragverma108/WildGuard#205]
Hi @anuragverma108  , I wanted to add your social media link in copyright text so users can navigate to your social profile and contact you easily please assign me this issue with hactoberfest label.
![image](https://github.com/user-attachments/assets/b18112c3-21ce-430e-abad-e2ff13e84d13)

thank you,
Pranav patil

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by Abhishekkamat33** [comment]
sir is issue still open ? If open you can assigned me .
