### ISSUE TITLE
Add social media icons in the page and also align the text in the landing page

### ISSUE THREAD

**Issue by RAVICHANDRALS507** [anuragverma108/WildGuard#207]
@rahulkhandait-sde 
@anuragverma108 
@PriyaGhosal 

**I want to work on this issue can you assign me this issue**

* In the Landing page the **text and the button is not aligned properly** 
* In the footer section **terms and use and privacy policy has been repeated**
* **Social media links has not been add yet** in the footer of the page.

![image](https://github.com/user-attachments/assets/ec42d715-0ba8-4743-b92b-4df1b50eda15)
![image](https://github.com/user-attachments/assets/dd74f090-6b97-4b33-a207-66876f02350a)

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
