### ISSUE TITLE
Feature Request: Implement Language Switch Functionality

### ISSUE THREAD

**Issue by Phani2425** [anuragverma108/WildGuard#21]
Issue Description:
The website currently has a language switch button, but it is non-functional. I would like to implement the functionality so that users can switch between different languages.

Proposed Solution:
- Add support for multiple languages using a JavaScript object or JSON file that contains the translations.
- Implement JavaScript logic to dynamically update the text content on the website when a user selects a language.
- Use a dropdown or buttons to allow users to choose their preferred language.
- Ensure real-time text updates without requiring a page reload.

I would like to work on this feature as part of Hacktoberfest. Could you please assign this issue to me and add the Hacktoberfest label?

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  

Happy open-source contributing! 🚀
