### ISSUE TITLE
Adding a Potrait image for mobile users

### ISSUE THREAD

**Issue by harshit69x** [anuragverma108/WildGuard#210]
![image](https://github.com/user-attachments/assets/1fa23f11-d4f2-44f3-87b2-4562949115c7)
As we can  see as we change the dimension of the screen, there is no image.

Please assign me this issue so that i can add an Image for the mobile view.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
