### ISSUE TITLE
Adding Login and Sign In Page 

### ISSUE THREAD

**Issue by SwarSpark** [anuragverma108/WildGuard#214]
I want to work on this issue can you assign me this issue

1. The Login and Sign UP/ Sign IN page has not been add yet.

I kindly request to be assigned this issue to enhance the functionality, usability, and visual appeal of the login and sign-in page.

Thank you!

Hactoberfest !!!

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label

**Comment by Pragya79645** [comment]
assign this to me
