### ISSUE TITLE
Create "Clear Ocean" Page

### ISSUE THREAD

**Issue by Sahil-xyz** [anuragverma108/WildGuard#217]
Hello @anuragverma108 ,
When we click on read more of clear ocean page it does not take us to new page. I would like to work on this issue.
Thank you !!
[ Hacktoberfest 2024]
![Screenshot 2024-10-02 200326](https://github.com/user-attachments/assets/067b7377-6be8-4cb5-8588-fcdacc2ec19b)

**Comment by anirudh-why** [comment]
would like to work on this issue.
