### ISSUE TITLE
Implement Photo Slider in Hero Section

### ISSUE THREAD

**Issue by Phani2425** [anuragverma108/WildGuard#22]
I would like to enhance the hero section of the website by adding an automatic photo slider feature. The goal is to have the background image of the hero section change automatically, while keeping the text and icons in the foreground static. This will improve the visual appeal of the homepage and make the website more dynamic.

Benefits:

-  Enhances the visual appeal of the hero section.
-  Makes the homepage more interactive and engaging for users.
-  Provides a smoother user experience with transitions.

I would like to work on this issue and contribute to this repository. Please assign me this issue under the Hacktoberfest label.

Thank you!

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  

Happy open-source contributing! 🚀
