### ISSUE TITLE
Repition of same Heading

### ISSUE THREAD

**Issue by Deepak0yadav** [anuragverma108/WildGuard#221]
1.Rise your hand to Save World animals life is repeated.
2."Our Mission " button is also two times 
3.Add on- Instead of "Rise" it should be "Raise"

**Comment by justbeingashutosh** [comment]
Hello @Deepak0yadav, I am interested in solving this issue. Please assign this issue to me.

**Comment by Deepak0yadav** [comment]
@justbeingashutosh ,But this issue has been resolved
