### ISSUE TITLE
Add Feedback Section in the Website

### ISSUE THREAD

**Issue by KanwalpreetSingh1823** [anuragverma108/WildGuard#223]
Please assign this issue to me under HactoberFest 2024

**Comment by KanwalpreetSingh1823** [comment]
I am waiting for your response.

**Comment by Smit1610** [comment]
@anuragverma108 Please assign this issue to me under HactoberFest 2024

**Comment by anirudh-why** [comment]
please assign this issue to me.

**Comment by justbeingashutosh** [comment]
Hello @anuragverma108, I am very interested in this issue. Please assign this issue to me! :)

**Comment by Pragya79645** [comment]
Assign this to me
