### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by Shobhit1729Aryan** [anuragverma108/WildGuard#231]
In "What we do" section, divs and headings are not properly aligned , we can work on it...

**Comment by dhruvaaArya05** [comment]
Hi @Shobhit1729Aryan, I would like to work on this issue. Please assign me this issue

**Comment by aditi-agrawal12** [comment]
Hello @Shobhit1729Aryan 
I want to work on this issue , as I have good command over HTML, CSS , I can resolve this issue.
Please assign this issue to me so that I can make my first opensource contribution 😊
