### ISSUE TITLE
Align the content to center of the website

### ISSUE THREAD

**Issue by justin212407** [anuragverma108/WildGuard#235]
Description
The website has misaligned text and content as it is aligned to the right of the website

Expected Behavior

it should be aligned to the center of the page.

Screenshots

![Screenshot 2024-10-02 212843](https://github.com/user-attachments/assets/802588ca-0fba-43e6-a2a8-551a5d3423c7)

![Screenshot 2024-10-02 212851](https://github.com/user-attachments/assets/df412bd6-92fe-4e7b-acf8-5738a3117f6e)

How to Reproduce
It is visible every time someone visits the site.

I would like to be assigned to this issue under hacktoberfest and would like to work on it.

**Comment by NawinKumarSharma** [comment]
@justin212407  can i work on this?

**Comment by justin212407** [comment]
> @justin212407 can i work on this?

This issue was resolved by somebody else hence closing it
