### ISSUE TITLE
add a community section and improve the transitions

### ISSUE THREAD

**Issue by kanikaa-3018** [anuragverma108/WildGuard#24]
please assign me this project for hacktoberfest24, im willing to contribute to the above issues

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by kanikaa-3018** [comment]
ok sir ill continue with this
