### ISSUE TITLE
 Footer section social media icon and contact by email or suggestion by email

### ISSUE THREAD

**Issue by VinayShah100** [anuragverma108/WildGuard#245]
The footer section of the project needs improvement by adding the following elements:

Social Icons: Add icons linking to popular social media platforms (e.g., Facebook, Twitter, Instagram, LinkedIn) in the footer for better user engagement and to increase social media visibility.

Suggestion/Comment Section via Email: Include a form or link where users can submit suggestions or comments directly through email. This will enhance user feedback and allow users to provide their input easily.

Tasks:

Add social media icons and ensure they are functional.
Design and implement a form or link for email suggestions or comments.
Ensure the footer is responsive and fits well with the overall design of the website.

![Screenshot 2024-10-02 224049](https://github.com/user-attachments/assets/1fe8e644-1312-494b-a59d-99b8cda20acc)

#241 #162

**Comment by VinayShah100** [comment]
Could you assign this issue to me?

**Comment by anuragverma108** [comment]
Assigned!
