### ISSUE TITLE
Add more languages.

### ISSUE THREAD

**Issue by swati-mishra07** [anuragverma108/WildGuard#25]
Add languages that enhance the searching capability in website .

**Comment by swati-mishra07** [comment]
@anuragverma108 There are only 3 languages and i think i add more languages.

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.
- Include the **issue number** in your PR description for better tracking.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by mironbarykin** [comment]
Hi, I would definitely like to help @swati-mishra07 in terms of such languages as **German** and **Russian**! I'm reachable by `barykinmiron@gmail.com` or `mironbarykin` via discord.

**Comment by swati-mishra07** [comment]
@mironbarykin Thankyou for this idea but i think i would more thankfull when we work on some other issue .

**Comment by AbhishekChamp879** [comment]
Hey @swati-mishra07 can i help in adding more languages. 
I have more to contribute can we work together
