### ISSUE TITLE
Add Contents for "Vision" and "Next Plan" Buttons on the Website

### ISSUE THREAD

**Issue by iAmDiksha** [anuragverma108/WildGuard#27]
I would like to work on adding content of the "Vision" and "Next Plan" sections under **why choose us** section. Currently, the "**Mission**" section is functional, but the "**Vision**" and "**Next Plan**" buttons do not display the associated content.

**### Proposed Solution:**

- Add JavaScript functionality to the "Vision" and "Next Plan" buttons.
- When a user clicks on the "Vision" button, the detailed vision statement will be displayed on the website.
- Similarly, clicking on the "Next Plan" button will show the planned future actions for the initiative.
- Ensure that the display of these sections is user-friendly and consistent with the existing design and behavior of the "Mission" section.

Please assign me this issue under **hacktoberfest** 2024.

**Comment by anuragverma108** [comment]
@iAmDiksha 
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
