### ISSUE TITLE
[Feat]: Latest News on Wildlife animal

### ISSUE THREAD

**Issue by mohitahlawat2001** [anuragverma108/WildGuard#28]
i can add section for latest news related to wildlife animal , which can dynamicly load from api

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
