### ISSUE TITLE
Adding a Marquee [constantly moving pictures] in the footer section

### ISSUE THREAD

**Issue by AADESHak007** [anuragverma108/WildGuard#283]
I think adding a marquee at the end of the website will make it look more interesting .The website is too static for the viewers and hence adding a marquee would make it more dynamic .
![Uploading Screenshot 2024-10-02 210329.png…]()

**Comment by the-asthabang** [comment]
kindly assign me this issue #283

**Comment by AADESHak007** [comment]
@the-asthabang I have already completed the task and raised PR for it . Just waiting for the review
