### ISSUE TITLE
Contact us Page is  missing

### ISSUE THREAD

**Issue by Varchasavkr** [anuragverma108/WildGuard#286]
there should a contact us page so that people can reach out to us in any case

https://github.com/user-attachments/assets/19252b9c-4ee3-4819-aa15-04e3795785f0

Kindly assign this to me @anuragverma108 @rahulkhandait-sde 

Thankyou

#hacktoberfest2024 #hacktoberfest-accepted

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me as i have done various projects using HTML, CSS and MERN
