### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by lord-cyclone100** [anuragverma108/WildGuard#29]
@anuragverma108 
I would like to add dark mode feature to your website
Please assign me this task under hacktoberfest 2024

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

We're excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by muskanyadav1134** [comment]
Can you please assign this to me?
