### ISSUE TITLE
Dark Mode Implementation 

### ISSUE THREAD

**Issue by AyushiChopra02** [anuragverma108/WildGuard#299]
the application currently lacks a dark mode feature, which can enhance user experience, especially in low-light environments.

To implement this, we can introduce a toggle button that adds a specific class to the body element, switching between light and dark themes. This will involve defining a separate set of CSS variables for dark mode colors, which will allow us to easily adjust the styling across different components.

Please assign this issue to me for Hacktoberfest 2024. Implementing this feature will provide users with greater flexibility and improve accessibility.

**Comment by AyushiChopra02** [comment]
@anuragverma108 assign this issue to me

**Comment by wankhadepranav** [comment]
@anuragverma108  please assign  me this issue
