### ISSUE TITLE
Addition of about section

### ISSUE THREAD

**Issue by AyushMann29** [anuragverma108/WildGuard#3]
![image](https://github.com/user-attachments/assets/e5a30cbc-7517-4ab3-9d9e-66c70a4b8b24)

In this, Our vision and Next Plan sections are empty and I want to add texts to them

**Comment by Sunil8wale** [comment]
Kindly assign me this issue under the Hacktoberfest 2024

**Comment by Sunil8wale** [comment]
@anuragverma108 kindly assign me this issue under the Hacktoberfest 2024

**Comment by anuragverma108** [comment]
Assigned @AyushMann29

**Comment by AyushMann29** [comment]
I added a pull request for this issue but cannot link to the issue for some reason. This is the PR ' Added text for about with 3 buttons #126 '
