### ISSUE TITLE
Add hover effect to "become a partner" button

### ISSUE THREAD

**Issue by justin212407** [anuragverma108/WildGuard#306]
Description
The website has a missing hover effect on the become a partner button

Expected Behavior

it should hover over the other content when clicked.

Screenshots

![Screenshot 2024-10-03 120330](https://github.com/user-attachments/assets/57e58dbc-85b6-47ce-951c-29f9e58dc43e)

How to Reproduce
It is visible every time someone visits the site.

I would like to be assigned to this issue under hacktoberfest and would like to work on it.

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024
