### ISSUE TITLE
Add hover effect to "Search Icon Button"

### ISSUE THREAD

**Issue by QaisarMoin** [anuragverma108/WildGuard#309]
Description
The website has a missing hover effect on the Search Icon button

Expected Behavior

It should show Green circle on hovering the Search Icon Button.

<img width="1443" alt="Screenshot 2024-10-03 at 12 10 29 PM" src="https://github.com/user-attachments/assets/eae06f95-b8fd-4186-b889-84c710e50859">

I would like to be assigned to this issue under hacktoberfest and would like to work on it.

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a Hacktoberfest contributor. Could you please assign it to me?
