### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by kartikey369-ind** [anuragverma108/WildGuard#31]
I would like to propose the addition of a Frequently Asked Questions (FAQ) section to our website. This section can address common queries that our users may have, providing them with quick and easy access to the information they need.

If you agree, I would be happy to take on the responsibility of gathering common questions and compiling them for the FAQ section.

@anuragverma108 , I would like to kindly request that this issue be assigned to me under the Hacktoberfest label. I am eager to contribute and work on resolving it. Thank you for considering my request.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by kartikey369-ind** [comment]
hi @PriyaGhosal @anuragverma108 
Iam getting merge conflict could you help me to avoid it

This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files
assets/css/style.css
assets/js/script.js
index.html

**Comment by kartikey369-ind** [comment]
![Screenshot_20241001-231332](https://github.com/user-attachments/assets/fef39fab-2fd4-4ca0-8afb-8671d6c84dd0)

Iam somewhat new to open source so could you please help me to resolve it

**Comment by kartikey369-ind** [comment]
done with the work please check my pr https://github.com/anuragverma108/WildGuard/pull/156
