### ISSUE TITLE
Add Volunteer Sign-Up Button with Form Redirection

### ISSUE THREAD

**Issue by SreyaSudheeran** [anuragverma108/WildGuard#32]
I propose creating a dedicated volunteer sign-up section on the website, enabling users to easily apply for volunteer opportunities at the wildlife sanctuary.

**Proposed Solutions:**
1. **Button Placement:**
- Add a prominent "Volunteer" button next to the donation button on the homepage.

2. **Form Page:**
- Create a new page to host the volunteer sign-up form.
- The form should collect essential information, including:
      Name
      Contact information (Email, Phone)
      Area of interest (Wildlife care, event support, community outreach, etc.)
      Availability (Full-time, Part-time, Weekends, etc.)
    
@anuragverma108 Sir, I would like to kindly request that this issue be assigned to me under the Hacktoberfest label. I am eager to contribute and work on resolving it. Thank you for considering my request.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
