### ISSUE TITLE
Add an interactive ChatBot 

### ISSUE THREAD

**Issue by VikrantKadam028** [anuragverma108/WildGuard#34]
Hello Sir,
It will be very beneficial if we added an interactive chatbot in the website, so that user can easily ask any questions regarding the website.
I kindly request u to assign this issue to me for Hacktoberfest 2024!!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
