### ISSUE TITLE
Adding About Us separate page

### ISSUE THREAD

**Issue by thechiranjeevvyas** [anuragverma108/WildGuard#341]
Hello @anuragverma108 ,

I propose the addition of an "About Us" page to our website. This page will outline the team who's working on the wildguard project and also it will be showcasing our commitment ,our vision ,our plan to protect wildlife. It will introduce the team members, their roles, and contributions, giving visitors insight into the people behind wildguard. This will enhance the credibility and transparency of our project helping visitors connect with our mission and the people driving it forward.

Kindly assign me this issue under Hacktoberfest 2024
Thanks

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me as i have done various projects using HTML, CSS and MERN
