### ISSUE TITLE
Image Gallery For different category Animals and seperate page for each.

### ISSUE THREAD

**Issue by rajlakshmi18704** [anuragverma108/WildGuard#35]
#35 
1.create a button in header to for image gallery.
2. Different category animals card will be shown.
3. onclicking the specific category, it will direct to the image page for the animal in that particular category,

 I can implement this.Assign this issue to me under hacktoberfest.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
