### ISSUE TITLE
TO KNOW WHAT IS THE NATIONAL WILD ANIMAL OF THE STATE THE DATA SHOWS ON FRONTEND POPUP

### ISSUE THREAD

**Issue by maahieummah** [anuragverma108/WildGuard#358]

**Comment by KanishkChhajed** [comment]
Hello, @maahieummah I would like to work on resolving this issue, but could you clarify what exactly needs to be done?

**Comment by maahieummah** [comment]
WHEN WE GET A STATE ANIMAL WE CAN EASILY GET THEM ALONG WITH ALL STATE DETAILS THROUGH ML CONCEPT

**Comment by KanishkChhajed** [comment]
@maahieummah So essentially, I need to build a model that assigns a state animal based on the state.

**Comment by maahieummah** [comment]
yes

**Comment by KanishkChhajed** [comment]
Okay I am working on it, please assign it to me
