### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by clydehenry3** [anuragverma108/WildGuard#38]
Hi there @anuragverma108!

I noticed in the mobile version of WildGuard that it looses the hero image. I would love to work on this issue. Additionally, I would love to redesign the 4 elements in the section so they fit with nice spacing. I am UX designer, web developer, and front end developer. Please see the referred sections below. 

Thank you!

<img width="472" alt="4 Elements" src="https://github.com/user-attachments/assets/4bba4c01-067e-4556-9823-95e72f39654c">
<img width="484" alt="Home Mobile Hero" src="https://github.com/user-attachments/assets/74228760-59c7-4fbb-b66c-f0a8ef7f0d4b">

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by clydehenry3** [comment]
@PriyaGhosal - Is there anyway you can link this to my PR #282? I forgot to add it within my PR and isn't showing for Hacktoberfest approval.

**Comment by DeviSriSaiCharan** [comment]
Hello, is anyone working on this issue?
