### ISSUE TITLE
Implement Login/Signup System 

### ISSUE THREAD

**Issue by Atharva-04** [anuragverma108/WildGuard#39]
👋 Hi there!

I'm excited to contribute to the WildGuard project! I’d like to propose adding a Login/Signup System for user authentication.

Why This Is Important:
User Personalization: Users can save preferences and track activities.
Security: Protects user data and builds trust.
Proposed Implementation:
Login/Signup Buttons: Add buttons to the navigation bar for easy access.
User Authentication: Implement a secure backend to manage user credentials.

![Navigation_Bar](https://github.com/user-attachments/assets/a9faa62f-d69f-44d5-b59f-2280691649bc)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
