### ISSUE TITLE
Add Contact-Us Section to the Website 

### ISSUE THREAD

**Issue by KanwalpreetSingh1823** [anuragverma108/WildGuard#4]
I would like to contribute in your website . I want to add Contact-Us Section in the website.

**Comment by anuragverma108** [comment]
Assigned @KanwalpreetSingh1823

**Comment by pranavmugatkar** [comment]
hi, I think contact us section is still not completed as I see on website so, can I do that

**Comment by Swadeeppatil** [comment]
I would like to contribute in your webpeg . I want to add Contact-Us Section in the website.  assign me this task under hacktoberfest
