### ISSUE TITLE
[BUG]: Become a partner button not working 

### ISSUE THREAD

**Issue by bhaavvya** [anuragverma108/WildGuard#40]
Description of an issue raised:-
"Become a partner" button is not working so, I would like to add a form for the partner to fill in details and add email facility.
The email facility can be changed to something you suggest.

@anuragverma108 , please assign me this issue under hacktoberfest 2024 and open for any suggestion.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
