### ISSUE TITLE
Feature Request: Add Login and Registration Page with Blurred Background Effect

### ISSUE THREAD

**Issue by achintyasrivastav** [anuragverma108/WildGuard#41]
I'd like to suggest adding a login and registration functionality to the project with a modern design. The idea is to have a modal popup for login/registration when a user clicks the "Login" or "Register" button. The popup should appear with a smooth animation, and the background should blur, providing a clean, user-friendly experience similar to many trendy designs.

Attaching the reference!
![Login](https://github.com/user-attachments/assets/4f640b4f-9a95-4e77-bcc2-254fbf2da1fc)

@anuragverma108, please assign me this issue under Hacktoberfest 2024. I'm open to any suggestions or feedback you may have!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
