### ISSUE TITLE
Add image carousel on banner-row for smaller screen width devices

### ISSUE THREAD

**Issue by prathameshrp** [anuragverma108/WildGuard#42]
On smaller screens, the banner row images look something like this:
![image](https://github.com/user-attachments/assets/89f377c7-b77f-4501-b30a-cba2956287b2)
And the user has to scroll a bit through these images to reach the next section.

To improve UI, we can add an image carousel that shows all images one after the other, or we can just add a faded slide show of images with some delay.

**Comment by adilkadivala** [comment]
hey @prathameshrp i want to contribute in this issue,  let assign it to me

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal-Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by PriyaGhosal** [comment]
@adilkadivala Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by prathameshrp** [comment]
#196
