### ISSUE TITLE
Instagram Logo Pop-up on Hover Fails to Redirect, Scrolls to Top Instead .

### ISSUE THREAD

**Issue by sarika00210** [anuragverma108/WildGuard#420]
Dear @anuragverma108 
#420
I noticed an issue on your website where hovering over the animal photo triggers the Instagram logo pop-up, but instead of redirecting to the Instagram page, it scrolls to the top of the site. As part of Hacktoberfest 2024, I'd be happy to resolve this bug and ensure proper functionality. Please let me know if I can assist with this fix.

Kindly assign me this issue under Hacktober fest 2024.

**Comment by sarika00210** [comment]
![Screenshot 2024-10-04 024248](https://github.com/user-attachments/assets/19191b3f-7df2-49e7-ace4-218fe0f1a424)

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a Hacktoberfest contributor. Could you please assign it to me?

**Comment by sarika00210** [comment]
It was identified by me earlier you have to connect with admin with some
new error
