### ISSUE TITLE
navbar width issue 

### ISSUE THREAD

**Issue by adilkadivala** [anuragverma108/WildGuard#43]
hey,  in small screen (tab, and mobiles) navbar goes out of screen,  so we should to fix it...

tab

![tab](https://github.com/user-attachments/assets/a4f97dba-47bb-42fb-be02-3a0fb0fe797d)

mobile L and mobile m (mobile medium screen)

![mobile425](https://github.com/user-attachments/assets/0e5aaf34-05ae-4638-8ca5-4d51d1520173)

mobile s    (mobile small screen)

![mobiles](https://github.com/user-attachments/assets/e1858641-daaa-4858-b94f-5100e566bc9c)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by adilkadivala** [comment]
thanks @PriyaGhosal for assigning it to me
