### ISSUE TITLE
Bottom to top scroll button

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/WildGuard#44]
I want to add the bottom to top scroll button so that user can directly scroll the page to top from bottom
![image](https://github.com/user-attachments/assets/e2246e81-5f91-4a27-a2c0-c0987152dba2)

**Comment by akhileshverma92** [comment]
Let's do it 🚀

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
