### ISSUE TITLE
Updated footer section with social media link and donation button 

### ISSUE THREAD

**Issue by VinayShah100** [anuragverma108/WildGuard#441]
new updated footer section for website with donation button 

![Screenshot 2024-10-04 110924](https://github.com/user-attachments/assets/9eaf3dca-b10f-4fb0-9de4-4b946dc76bd4)

#162

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024
