### ISSUE TITLE
Add Underline Transition Effect to Navbar Links

### ISSUE THREAD

**Issue by suasha123** [anuragverma108/WildGuard#447]
This issue proposes adding an underline transition effect to the navigation links in the navbar. The aim is to enhance user interaction by providing a smooth visual , when hovering over each link without affecting other styles or the positioning of the navbar elements.

Before:

https://github.com/user-attachments/assets/8a37d8a1-4179-4efa-875f-e5fcf7f32e68

After : 

https://github.com/user-attachments/assets/b2f71cdf-225f-469b-b51d-85d3bd010422

**Comment by codebydeep** [comment]
Heyy @suasha123 , I want to contribute to this issue. Please assign this to me.

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a Hacktoberfest contributor. Could you please assign it to me?

**Comment by suasha123** [comment]
> Hello! I’m excited to work on this issue as a Hacktoberfest contributor. Could you please assign it to me?

I have alredy did pr !!! Sorry :(. 
Let's collab on something else if you don't mind
