### ISSUE TITLE
Adding header section and footer section in Contact us Page to improve overall UI

### ISSUE THREAD

**Issue by AmulyaJain2004** [anuragverma108/WildGuard#449]
The current "Contact Us" page for WildGuard can be improved to enhance user experience, accessibility, and interactivity.
Adding header section and footer section in this page would make it connected to theme of the website and also improving some small UI enhancement such as loading animation upon sending form  and WildGuard logo with title (favicon) etc. will improve the overall page.

**Comment by Adil-Khan-N** [comment]
Can you assign this issue to me?
