### ISSUE TITLE
Want to add the functionality for open search option 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [anuragverma108/WildGuard#45]
I want to add a functionality in navbar so that user can open the search bar 

![image](https://github.com/user-attachments/assets/8fad79ee-5016-4840-a879-1f12beedce37)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024
