### ISSUE TITLE
Add Dark Mode Theme and Basic Animations

### ISSUE THREAD

**Issue by ankit071105** [anuragverma108/WildGuard#46]
# Description
We need to implement a dark mode theme to improve user experience, especially in low-light environments. Additionally, basic animations will be added to enhance the user interface's responsiveness and interactivity.
# Technologies:
CSS: For theme styles and animations (e.g., @keyframes, transform, transition).
JavaScript: For handling the dark mode toggle and persisting user preferences using localStorage.
# Expected Outcome:
A fully functional dark mode theme toggle.
Smooth, subtle animations that enhance user interaction.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
