### ISSUE TITLE
Proposal to Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Mayursoni1518** [anuragverma108/WildGuard#47]
I noticed the project lacks a CONTRIBUTING.md file. I'd like to create this file to provide guidelines on contribution standards, pull request procedures, and coding practices. This will help streamline collaboration and ensure consistency across contributions.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by Mayursoni1518** [comment]
I have attached the Contributing.md file and please cheak out and merge it ...?
