### ISSUE TITLE
Add a "Terms of Use" page to the project

### ISSUE THREAD

**Issue by NehanPathan** [anuragverma108/WildGuard#48]
### **Issue Title:**
Add a "Terms of Use" page to the project

### **Issue Description:**
We need to add a "Terms of Use" page to provide users with clear guidelines and conditions for using the application. The page should be a separate HTML file that can be linked from the main HTML page of the project. The following tasks need to be completed:

- Create a `terms-of-use.html` page with the necessary structure.
- Include a section with placeholder text for the terms and conditions, which can be updated later.
- Add a navigation link in the main HTML file (e.g., `index.html`) to redirect users to the "Terms of Use" page.

**Acceptance Criteria:**
- A new `terms-of-use
- .html` page is created with placeholder text for the terms.
- The main HTML file has a working link that navigates to the "Terms of Use" page.
  
---

**Comment by PriyaGhosal** [comment]
@NehanPathan Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
