### ISSUE TITLE
subject : changing the content and adding good content

### ISSUE THREAD

**Issue by SadafKausar2025** [anuragverma108/WildGuard#493]
![Screenshot (2463)](https://github.com/user-attachments/assets/3173301d-c680-4540-bbd8-6b899f90dc5f)

I want to change the content in this event boxes
All boxes are having same content . so i want to correct it

please assign this issue to me for hacktoberfest

**Comment by Dinkar850** [comment]
![Screenshot (1103)](https://github.com/user-attachments/assets/c08f8683-8316-470d-8b40-17bc2361fae9)

I wish to change this content and other content of the website as well, so please assign me this issue.
