### ISSUE TITLE
Implement Themed "Scroll to Top" Button for Better Usability on WildGuard

### ISSUE THREAD

**Issue by piyushshrma** [anuragverma108/WildGuard#5]
To align with the mission of **WildGuard** and enhance the **user experience**, I propose the addition of a "**Scroll to Top**" button that matches the theme of the website. This feature will allow users to easily navigate back to the top of the page, especially on pages with extensive content, such as those showcasing various charity initiatives. By incorporating the same design elements as the existing site, the button will seamlessly blend into the aesthetic while improving navigation. This will provide a more fluid and user-friendly experience for visitors, helping to keep them engaged in **WildGuard's important mission of saving world animals**.

Kindly assign me this issue under **Hacktoberfest 2024**.

**Comment by maniranjan2023** [comment]
Added a custom-themed "Scroll to Top" button to improve the user experience on WildGuard. This button allows users to quickly navigate back to the top of the page, enhancing overall accessibility and usability. The theme is consistent with the site's design for a seamless look and feel.

please assign this issue to me
