### ISSUE TITLE
No donation link

### ISSUE THREAD

**Issue by rajatuiwebdev** [anuragverma108/WildGuard#50]
Hey there! I noticed that the donation button on the main page doesn't currently function. To make the website more realistic and interactive, I can create a functional donation page that allows users to contribute to wildlife conservation.

I request you to kindly assign me this issue under Hacktoberfest, thank you! @anuragverma108

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
