### ISSUE TITLE
Add Privacy Policy Page to the Project

### ISSUE THREAD

**Issue by NehanPathan** [anuragverma108/WildGuard#51]
### Issue Title
Add Privacy Policy Page to the Project

### Issue Description
**Description:**
We need to create a dedicated "Privacy Policy" page for our WildGuard project to inform users about how their data is handled and protected. This page will be accessible from the main HTML file.

**Tasks:**
- Create a new HTML file named `privacy-policy.html`.
- Include the following sections in the privacy policy:
  - Introduction
  - Information Collection
  - Use of Information
  - Data Protection
  - User Rights
  - Changes to the Privacy Policy
- Link the new Privacy Policy page in the footer/header of the main HTML file.
- Ensure that the design is consistent with the overall theme of the website.

**Acceptance Criteria:**
- The Privacy Policy page should be well-structured and readable.
- Users should be able to easily navigate to the Privacy Policy page from the main website.
- The page should be responsive and work well on both desktop and mobile devices.

**Comment by akhileshverma92** [comment]
Let's do it

**Comment by PriyaGhosal** [comment]
@NehanPathan Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
