### ISSUE TITLE
Home page could be better 

### ISSUE THREAD

**Issue by ayushrskiaa** [anuragverma108/WildGuard#524]
please assign me this work under hacktoberfest
thank you

**Comment by uvenkatateja** [comment]
i want to make home page should be more attractive by using shadcn or antd libraries
please assign me this work under hacktoberfest
thank you

**Comment by ayushrskiaa** [comment]
![image](https://github.com/user-attachments/assets/d53bf93f-a590-4915-96f0-9b96497c9c5d)
The navbar is not aligned properly I can fix that.
