### ISSUE TITLE
Enhancement: Add a Frequently Asked Questions Section, Responsive for All Screen Sizes

### ISSUE THREAD

**Issue by Sancharisingh** [anuragverma108/WildGuard#544]
<img width="1439" alt="Screenshot 2024-10-05 at 3 29 52 PM" src="https://github.com/user-attachments/assets/0dcd817d-2673-4ad6-915f-d752dd22e184">

Create an accordion-style FAQ section to enhance the website's usability and organization.<br>
Ensure that each question smoothly expands upon clicking, revealing the answer underneath for better clarity.<br>
Incorporate animations for a seamless transition between opened and closed states, improving the overall user experience.<br>
Design the FAQ section to resemble modern interfaces, making it visually appealing and user-friendly.

**Comment by GT0SRT** [comment]
i updated faq section made it responsive...
![image](https://github.com/user-attachments/assets/14342827-af5b-4b98-9244-969f5fc1fc86)
