### ISSUE TITLE
Improve Header Responsiveness on Mobile Screens

### ISSUE THREAD

**Issue by Shivaraj2003** [anuragverma108/WildGuard#57]
Navbar is not responsive on mobile screens.
Needs CSS media queries to collapse and adapt to smaller dimensions.I want to contribute for this.
Please assign this issue to a participant for **Hacktoberfest 2024**. 
Thank you!

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
