### ISSUE TITLE
Add some important button to avoid scroll

### ISSUE THREAD

**Issue by Anurag25021** [anuragverma108/WildGuard#571]
I want to add some button below the navbar so that the user can easily find things like FAQ's , About us And Home and avoid scrolling to find things.

**Comment by KirtiPandey19** [comment]
Hello,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
