### ISSUE TITLE
Fix  UI and UX

### ISSUE THREAD

**Issue by rahulholkar16** [anuragverma108/WildGuard#574]
Hello @anuragverma108 , I want to fix the UI and UX of Your webpage.
Please assign me this issue with the Hacktoberfest Label.

**Comment by KirtiPandey19** [comment]
Hello @anuragverma108,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
