### ISSUE TITLE
Solving issues regarding navigation

### ISSUE THREAD

**Issue by patilpratik1905** [anuragverma108/WildGuard#577]
I would like to help making this website better by contributing and making the following changes
1) adding the pages for - a)learn more b)the what-we-do block where there are 4 links learn more
2) adding proper logic for raised,to-go,goal and showing proper achieved percentage rate
3) giving images a professional look

**Comment by KirtiPandey19** [comment]
Hello @anuragverma108,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
