### ISSUE TITLE
Contact Us Page Enhancements

### ISSUE THREAD

**Issue by Mandipbhattarai** [anuragverma108/WildGuard#580]
This issue focuses on improving the Contact Us page for the WildGuard web application by implementing the following changes:

Visual Design Improvements: Enhanced the overall design to make the page more attractive and user-friendly.
Action Buttons: Added prominent action buttons for "Email Us" and "Contact Us" to streamline user interactions.
These updates aim to enhance user engagement and satisfaction with the Contact Us page.

**Comment by Pragya79645** [comment]
Please assign me with tis issue. I would like to work on it.
