### ISSUE TITLE
Added Link in Dontation.html NavBar

### ISSUE THREAD

**Issue by Dubey123f** [anuragverma108/WildGuard#583]
In Donation.html there is an issue  due to which we can not return to our homepage directly and anywhere.
![Screenshot 2024-10-06 113424](https://github.com/user-attachments/assets/7dc94216-65c4-4a97-81b5-60f49c7e0cad)

**Comment by KirtiPandey19** [comment]
Hello @anuragverma108,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
