### ISSUE TITLE
Image Quality Issue: Blurry and Low Resolution

### ISSUE THREAD

**Issue by ketan270** [anuragverma108/WildGuard#587]
I have noticed that the image displayed in [specific location or context, e.g., "the homepage," "the product page," etc.] appears blurry and is of low resolution. This affects the overall quality and user experience.

Steps to Reproduce:
Navigate to [specific location].
Observe the image displayed.
Notice the lack of clarity and detail.
Expected Result:
The image should be clear and high-resolution, providing a better visual experience.

Actual Result:
The image appears blurry and lacks detail, making it difficult to view properly.

Suggested Actions:
Replace the current image with a higher resolution version.
Ensure that the image is optimized for web display without sacrificing quality.
Thank you for looking into this issue!

**Comment by ketan270** [comment]
Assign

**Comment by TanishaBansal101** [comment]
The images on the project appear blurry and are of low resolution, making them look unprofessional and difficult to engage with.

Simply enlarging the images didn’t help, as it led to more pixelation.
Changing file formats did not resolve the clarity issue.

Using High-Resolution Images: Sourcing images that are specifically designed for high quality.
Image Optimization Tools: Utilizing online tools or software to compress images without sacrificing resolution.
Incorporating Visual Effects: Adding overlays or effects (like gradients or shadows) can create a more dynamic look, even if the image quality is not perfect.

Please assign me to resolve this issue.
