### ISSUE TITLE
 adding a hover effect on the "Our Mission," "Our Vision," and "Next Plan" buttons,

### ISSUE THREAD

**Issue by Swadeeppatil** [anuragverma108/WildGuard#59]
Hi @anuragverma108 ,

the issue regarding adding a hover effect on the "Our Mission," "Our Vision," and "Next Plan" buttons, and I would love to contribute. Please assign me this issue under hacktoberfest.

**Comment by PriyaGhosal** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!

**Comment by Swadeeppatil** [comment]
ok 
can i  add  frequently ask question sectiom on webpeg
