### ISSUE TITLE
Improve UI of Footer on the Landing Page

### ISSUE THREAD

**Issue by Dipu2552003** [anuragverma108/WildGuard#590]
Description: The current footer design on the landing page could be enhanced for better visual appeal and user experience. The suggested improvements include:

Layout Redesign: Organize the footer sections more intuitively, ensuring key links like Contact Us, Privacy Policy, and Terms of Service are easily accessible.
Responsive Design: Ensure the footer displays correctly across all devices (mobile, tablet, and desktop), maintaining a consistent look.
![footer](https://github.com/user-attachments/assets/38ce9231-7741-444a-871f-b7456fa0cdb1)

**Comment by Sagarporwa1** [comment]
Hello @Dipu2552003 ,

I hope you're doing well! I came across issue #590 regarding Improve UI of Footer on the Landing Page. I’m really interested in contributing to this project, and I believe my skills in html and css make me a good fit to address this issue.

I’d love to take this on and help out. Could you please assign me to this issue? If there are any specific guidelines or expectations, I'd be happy to follow them.

Thank you for considering my request. I look forward to contributing!

Best regards,
Sagar Porwal
Sagarporwa1

**Comment by Sagarporwa1** [comment]
Hello @anuragverma108 ,

I hope you're doing well! I came across issue #590 regarding Improve UI of Footer on the Landing Page. I’m really interested in contributing to this project, and I believe my skills in html and css make me a good fit to address this issue.

I’d love to take this on and help out. Could you please assign me to this issue? If there are any specific guidelines or expectations, I'd be happy to follow them.

Thank you for considering my request. I look forward to contributing!

Best regards,
Sagar Porwal
Sagarporwa1

**Comment by Sagarporwa1** [comment]
Hello @anuragverma108 ,
I hope you're doing well! i came across issue #592 regarding improve ui of footer on the landing page.
I’m really interested in contributing to this project, and i believe my skills in html and css make me a good fit to address this issue. i’d love to take this on and help out. 
could you please assign me to this issue? if there are any specific guidelines or expectations, i'd be happy to follow them. thank you for considering my request. i look forward to contributing! best regards, sagar porwal sagarporwa1

**Comment by mohammed-anwar404** [comment]
Hey, I have made a PR on this issue. Please check it and let me know.
