### ISSUE TITLE
Hero Section Layout Issue

### ISSUE THREAD

**Issue by DeviSriSaiCharan** [anuragverma108/WildGuard#593]
## Description:
In the hero section of the website, there is a layout issue where the "Donation" buttons overlap with the text and each other. This disturbs the visual design and user experience. The affected area is the section that highlights the cause, "Defending Wildlife, One Paw at a Time," and the adjacent donation buttons.

## Screenshots:
![image](https://github.com/user-attachments/assets/a8c4c121-f43a-4557-bd86-5cdb4f846b9e)

**Comment by KirtiPandey19** [comment]
Hello @anuragverma108,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
