### ISSUE TITLE
Add Box Styling to Navbar Links for Enhanced Visual Appeal on WildGuard

### ISSUE THREAD

**Issue by piyushshrma** [anuragverma108/WildGuard#61]
To improve the visual hierarchy and navigation clarity on the WildGuard website, I propose adding box styling around the navbar links such as Home, About, Services, and more. This design enhancement will not only make the navigation options stand out more but also contribute to a cleaner and more structured layout. The box styling will align with the overall theme of the website while making it easier for users to locate and interact with key sections, thereby improving user engagement and the overall browsing experience.

Kindly assign me this issue under Hacktoberfest 2024.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
