### ISSUE TITLE
Issue: To work on CSS and add animations

### ISSUE THREAD

**Issue by AratrikaDas2024** [anuragverma108/WildGuard#612]
Hello @anuragverma108 

I would like to contribute by working on CSS and add some animations to the webpage.

Please assign this task to me under Hacktober2024.

**Comment by KirtiPandey19** [comment]
Hello @anuragverma108,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.
