### ISSUE TITLE
improving the css styling and hovering effects

### ISSUE THREAD

**Issue by mishrasushant101** [anuragverma108/WildGuard#616]
Hello @anuragverma108 . 
i am a full stack web developer and and have a special interest in designing i have cloned multiple websites like netflix ,spotify (you can see my repos) so i would be glad if you assign me this issue of styling it and making the hovering effect prettier.
 Kindly assign me this issue under Hacktoberfest 2024

**Comment by KirtiPandey19** [comment]
Hello,
I am actively participating in Hacktoberfest 2024. I came across your repository, and I am very interested in contributing to it. I would love to work on this repo or any other task where you feel I can provide value. So Please assign me this repo.

**Comment by PrajaktaPatil05** [comment]
Add More Styling to the Website

Hello, I'm a full stack developer participating in Hacktoberfest and I'd love to contribute to enhancing the CSS styles of this project. I would like to:

Improve the layout by updating the header, footer, and navigation bar.
Modernize the buttons and forms to create a better user experience.
Make the website responsive for various screen sizes.
Could you please assign this task to me? I will follow the contribution guidelines and ensure everything aligns with the project's vision.

Looking forward to contributing!
