### ISSUE TITLE
The Donate Button's is not styled properly

### ISSUE THREAD

**Issue by danishsheikh1122** [anuragverma108/WildGuard#629]
The open icon '>' is not aligned to the right of the button.
I can fix it please assign this issue to me 

see the icon '>' is appearing below the donate button. 
<img width="454" alt="Screenshot 2024-10-07 at 12 01 42 PM" src="https://github.com/user-attachments/assets/3209040d-2f80-484f-a1e6-99922d4316e3">

**Comment by LOKENDRA2006** [comment]
hye @anuragverma108 please assign me this work.
