### ISSUE TITLE
Add a Issue & PR Template 

### ISSUE THREAD

**Issue by anuragverma108** [anuragverma108/WildGuard#63]
If anyone wants to contribute under Hacktoberfest 2024 then do comment, I will assign it to you.

**Comment by rajlakshmi18704** [comment]
I want to contribute  on issue #35 which is raised by me under Hacktoberfest 2024 .

**Comment by anuragverma108** [comment]
@Sthorat22 The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by alvin-dennis** [comment]
@anuragverma108 can i add the issue template and the pr template . pls assign this to me under hacktoberfest

**Comment by Ritik-Singh21** [comment]
I want to contribute for Hacktoberfest 2024 .
