### ISSUE TITLE
 "Feature Request: Add 'Go to Top' Button in Footer"

### ISSUE THREAD

**Issue by sadique-2004** [anuragverma108/WildGuard#632]
Hi [@anuragverma108 ],

I'd like to contribute to this project by adding a useful feature. I propose adding a "Go to Top" button in the footer section of the website/application.

Rationale:

- Enhances user experience by providing easy navigation
- Improves accessibility for users who scroll through long pages
- Consistent with modern web design conventions

Expected Outcome:

- A clickable button labeled "Go to Top" or an appropriate icon (e.g., ↑)
- Button is positioned in the footer section
- Upon clicking, the button scrolls the page to the top

**Comment by Akshat1276** [comment]
Hi
I'd like to add the 'go to bottom' page as well. Kindly assign me this issue under Hacktoberfest '24
Thanks
