### ISSUE TITLE
Adding Information on View Event Button . 

### ISSUE THREAD

**Issue by Sthorat22** [anuragverma108/WildGuard#67]
![image](https://github.com/user-attachments/assets/7f919130-1273-43d4-83c2-aab9e7ede2bf)
Add information of events so whenever clicked on view event Button it will be redirected to that events information page.

Hacktober 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
