### ISSUE TITLE
Adding Data to Become a Partner button.

### ISSUE THREAD

**Issue by Sthorat22** [anuragverma108/WildGuard#68]
![image](https://github.com/user-attachments/assets/1c4b3e0a-8885-4f1e-90a1-7e8ddf1e2d39)
1.Agreement: Consent to terms and partnership conditions.
2.Basic Contact Info: Name, email, phone.
3.Partnership Type: Choose between sponsor, donor, or event partner.

HacktoberFest2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
