### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Bhanvi2204** [anuragverma108/WildGuard#684]
There is an issue in the navbar .The navbar is not very visually appealing. The navbar options are not correctly positioned, and the height of the navbar is not ideal for the website. The underline under the Home option is not looking good, i would like to change its UI
![Screenshot 2024-10-08 152011](https://github.com/user-attachments/assets/a562f06f-257b-43c5-aeed-20fd77f9ae84)
.

**Comment by kanishk1234567890** [comment]
Hy
can I also try to contribute and make the UI better and more visually appealing?
