### ISSUE TITLE
Add Donation page to website.

### ISSUE THREAD

**Issue by srinidhifd** [anuragverma108/WildGuard#7]
I would like to add a donation page to this website . This will help users know more about the Wild Guard and how they can help financially.

@anuragverma108 Please assign this issue under hacktoberfest label.
Thank you

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by srinidhifd** [comment]
@anuragverma108 I wanted to work on this but somebody has already created this page . I can see it in website. You can close this issue . I will find latest bugs in website and raise news issues .Thank you
