### ISSUE TITLE
Fix the height of the Navbar 

### ISSUE THREAD

**Issue by Vixs101** [anuragverma108/WildGuard#73]
Hi, i suggest we fix the height of the Nav bar, as it's to big at the moment and not that appealing to the eye.
![image](https://github.com/user-attachments/assets/542cebbd-59a9-4743-b409-ee3f6cb3b3c2)

**Comment by PriyaGhosal** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
