### ISSUE TITLE
login page in struck and not in right position

### ISSUE THREAD

**Issue by Ganesham09** [anuragverma108/WildGuard#737]
![Screenshot 2024-10-08 222908](https://github.com/user-attachments/assets/94886df5-734b-48b6-9c39-c22b0d998468)
 in this screen shot we can clearly see that the login page is not at right position and not when we click on that again there is no resposnse

**Comment by adilkadivala** [comment]
hey @Ganesham09 ,  I have solved it ,  
look at  #694,
https://github.com/anuragverma108/WildGuard/issues/694

and i have rised PR with corosponding solution

here is PR solved #694 #761
https://github.com/anuragverma108/WildGuard/pull/761
