### ISSUE TITLE
Adding relevant information in Service/Save Nature in service-card div

### ISSUE THREAD

**Issue by yeshwanth-ds** [anuragverma108/WildGuard#78]
**Before :**
`
![Before](https://github.com/user-attachments/assets/11b8b082-034d-4890-a0d0-da869dc6447f)
`
**Changes I propose :**
`
![After](https://github.com/user-attachments/assets/3f0ba69c-1b4a-452e-94ee-0d030adcb80c)
`

**Comment by anuragverma108** [comment]
Thanks for creating the issue in *WildGuard*! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
