### ISSUE TITLE
Adding a proper Login/Register tile on clicking login/register in navbar

### ISSUE THREAD

**Issue by antilpiyush89** [anuragverma108/WildGuard#784]
Adding a proper Login/Register tile on clicking login/register in navbar

Right Now it looks like this 

https://github.com/user-attachments/assets/4c3c8078-abeb-42f2-ac8f-c58f05720fed

Assign me this issue so i can fix this

**Comment by MOHIT-IITP** [comment]
@antilpiyush89 i have raised the same issue #770  , and also worked on it
