### ISSUE TITLE
Adding relevant information in Service/Save Nature in service-card div

### ISSUE THREAD

**Issue by yeshwanth-ds** [anuragverma108/WildGuard#79]
**Before :**
![Before](https://github.com/user-attachments/assets/8bfe098e-4613-4c29-aa2a-6c5d80d4e683)

**Changes I propose**
![After](https://github.com/user-attachments/assets/8957336f-422f-48f6-b63c-57f86caac2ed)

**Comment by PriyaGhosal** [comment]
This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
