### ISSUE TITLE
Add Service page to the website.

### ISSUE THREAD

**Issue by srinidhifd** [anuragverma108/WildGuard#8]
I would like to add a service page to this website. This page will inform users about the various services provided by Wild Guard and how they can contribute to wildlife conservation efforts through their involvement.

@anuragverma108 Please assign this issue under hacktoberfest label.
Thank you

**Comment by anuragverma108** [comment]
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Swadeeppatil** [comment]
i would like to add service peg  in this website. .this peg  infrom to user what type of services provided
@anuragverma108  plz assign me this issue  under hacktoberfest label.

**Comment by srinidhifd** [comment]
@anuragverma108 many have already done like this pages should I still work on this, or raise other issues?
