### ISSUE TITLE
Animals Images Not align Properly 

### ISSUE THREAD

**Issue by agnijeetsharma** [anuragverma108/WildGuard#84]
Images should be properly aligned in a responsive layout. They should maintain proper spacing and not overlap regardless of the screen size (desktop, tablet, or mobile). The layout should be clean and visually balanced across all devices.

consider this issue under hacktoberfest

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
