### ISSUE TITLE
No proper alignment of searchbar and search icon

### ISSUE THREAD

**Issue by mohamedfarhan-m** [anuragverma108/WildGuard#845]
hi sir, I am beginner in the world of opensource contribution and lucky to have supporters and mentors like you I have seen the issue on the navbar where there is no space between searchbar and searchicon. which is not looking good at all. I want to work on this issue. Please assign me this issue. the issue related image has been added.
![hacktber](https://github.com/user-attachments/assets/20f4bde3-6f61-4d9b-b6c6-11e194259393)

**Comment by Rajatrahangdale** [comment]
hi @mohamedfarhan-m ..!, please check my issue id: #836 I have already worked on it. 
please check billow Screen shot. 
![Screenshot 2024-10-10 012135](https://github.com/user-attachments/assets/29569a08-fe06-4579-be9c-c505d4e17253)

if you want to add extra into it. it will be appreciated.

**Comment by mohamedfarhan-m** [comment]
@Rajatrahangdale  I have added space between search area and search icon
