### ISSUE TITLE
Remove "Stay Connected" text from Footer

### ISSUE THREAD

**Issue by Soumipal56** [anuragverma108/WildGuard#855]
Problem - The 'Stay Connected' text appears on the footer of the homepage and is no relevant or necessary for the current design.

Expected Behavior - The text should be removed from the footer.

Steps to Reproduce - 
1. Visit the homeage.
2. Scroll to the footer.
3. Observe the 'Stay Connected' text.

Additional Context - Removing this will help simplify the layout and focus on important content.

**Comment by Aaqilyousuf** [comment]
@anuragverma108, can you assign this issue to me?

**Comment by Pragya79645** [comment]
please assign me with this
