### ISSUE TITLE
Add hover effect to buttons in the "Why Choose Us" section for improved UI

### ISSUE THREAD

**Issue by Nikhileshmauje** [anuragverma108/WildGuard#86]
I suggest adding a hover effect to the buttons in the 'Why Choose Us' section to enhance the user experience and make the UI more engaging. A subtle hover effect will highlight each button as the user interacts with it, providing a more polished and interactive feel. Let me know if this would be a good enhancement!

@anuragverma108  If you Agree, Please assign this to me.

**Comment by Deepak0yadav** [comment]
yes its also missing out there

**Comment by rahulkhandait-sde** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @rahulkhandait-sde - Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
