### ISSUE TITLE
Centered the search button in index file

### ISSUE THREAD

**Issue by Kedar-sonavani** [anuragverma108/WildGuard#891]
![Screenshot 2024-10-11 105343](https://github.com/user-attachments/assets/0fa3807f-b1af-4d38-aecf-5403db44c265)
![image](https://github.com/user-attachments/assets/013c3600-1e7e-4728-b9f3-2f68208967c1)

**Comment by rookieanvesh** [comment]
hey leads, i would like to contribute to this
