### ISSUE TITLE
Add Search Functionality to the Navigation Bar

### ISSUE THREAD

**Issue by srinidhifd** [anuragverma108/WildGuard#9]
The search icon in the navigation bar is currently not functional. We need to implement search functionality that allows users to search for content on the website. The search bar should be triggered when clicking the search icon. 
It should include the following features:

- Auto-complete suggestions
- Search results page that displays relevant content

![search](https://github.com/user-attachments/assets/87450ddf-b447-474f-b2d0-2f082be3923b)

@anuragverma108 Please assign this issue under hacktoberfest label.
Thank you

**Comment by anuragverma108** [comment]
@srinidhifd 
Thanks for creating the issue in **WildGuard**! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach **before & after screenshots** in your PR for clarity.

I'm excited to see your contribution as part of **Hacktoberfest 2024**! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
