### ISSUE TITLE
Unnecessary width of navbar and inappropriate design of donate box

### ISSUE THREAD

**Issue by dhruvi6071** [anuragverma108/WildGuard#91]
In this site it is really a well design site but the issue is that navbar has unnecessary width which catch more user's eyes in negative way. Also the donate box has out line pattern which seem quite off in the design and also when i hover that disappear which makes it more unpleasant feature. I would like to solve this issue. 
![Screenshot 2024-10-01 200202](https://github.com/user-attachments/assets/1ce1239d-ae5e-4658-a238-0ac3a46b0600)
![Screenshot 2024-10-01 200330](https://github.com/user-attachments/assets/6ffe154b-1e16-4549-8fa3-ab18d33c2802)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
