### ISSUE TITLE
Home page icon gets hidden by view event button

### ISSUE THREAD

**Issue by dhruvi6071** [anuragverma108/WildGuard#92]
In this site view event button keeps hiding the home button which is unpleasant to look and also kill good user experience.
I would like to change this into more user friendly issue. 
Please assign me this issue under hectoberfest2024 !!
![img1](https://github.com/user-attachments/assets/bb431b7d-8023-4234-b6fc-b3cd075df4aa)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
