### ISSUE TITLE
#Add Impact Gallery Section

### ISSUE THREAD

**Issue by prakruthiprasad20** [anuragverma108/WildGuard#925]
I would like to enhance the website by adding an Impact Gallery Section. This feature will visually showcase the positive effects of donations, allowing visitors to see the real-world impact of their contributions on wildlife conservation efforts.

 A dedicated space to highlight the achievements made possible by donor contributions can be added. An Impact Gallery will not only inform visitors but also inspire them to support cause by illustrating the tangible benefits of their donations.

**Comment by Malay207** [comment]
Hi @anuragverma108 , I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

**Comment by prakruthiprasad20** [comment]
Hey @anuragverma108 , can you also please add the gssoc-ext label too
