### ISSUE TITLE
#To complete the registration form.

### ISSUE THREAD

**Issue by prakruthiprasad20** [anuragverma108/WildGuard#929]
The registration button already exists but is not working and opening, it needs to be corrected.

**Comment by Malay207** [comment]
I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

**Comment by SparshMadaan** [comment]
@prakruthiprasad20 what exactly the issue can u please share an image or video ?

**Comment by prakruthiprasad20** [comment]
Hey, @anuragverma108 can you please add the "gssoc-ext" label too
