### ISSUE TITLE
Missing Hovering effect on Language Selection Button

### ISSUE THREAD

**Issue by Deepak0yadav** [anuragverma108/WildGuard#93]
Hey, Hovering effect is not working on moving Cursor to Language Selection Button ...We should fix that 

https://github.com/user-attachments/assets/935a2001-df64-429e-93ff-eff19adfa0d2

**Comment by kavya-r30** [comment]
My name is Kavya, and I would like to add the hovering effect on Language selection button. I plan to include relevant information that supports your website's mission and ensures the content aligns with the design of the index page, making it user-friendly and cohesive.

Would you please assign me this task under the Hacktoberfest 2024 tag

**Comment by Deepak0yadav** [comment]
Please assign me this task for Hactoberfest 2024

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
