### ISSUE TITLE
Add Search bar

### ISSUE THREAD

**Issue by Deepak0yadav** [anuragverma108/WildGuard#94]
Hey, Search bar is missing out there in Navbar, We should add it or remove the search button because only Search button is present which does not makes any sense
![Screenshot 2024-10-01 201917](https://github.com/user-attachments/assets/7d2f404a-ebe1-4c90-82d3-c3f065801694)

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
