### ISSUE TITLE
Amazing animation in website's  different sections

### ISSUE THREAD

**Issue by akhileshverma92** [anuragverma108/WildGuard#96]
Issue Description:

I am working on implementing smooth animations in different sections of a website using HTML, CSS, and JavaScript. The goal is to create engaging animations as users scroll or interact with various parts of the page.

Goals:

Implement smooth animations in different sections of the website (e.g., hero section, content sections, footer).
Ensure that animations trigger based on scroll position or user interactions.
Optimize animations for performance and responsiveness on different devices (desktop, tablet, mobile).
Details:

Hero Section:
Implement a CSS/JS-based fade-in and sliding effect for the hero text and images on page load.
Content Sections:
As the user scrolls, trigger animations like a staggered fade-in or sliding of content blocks using vanilla JavaScript and CSS keyframes.
Footer:
Apply a smooth entry animation for the footer elements, such as a fade-in from the bottom or a subtle scale effect when the footer comes into the viewport.
Challenges:

Ensuring smooth performance across all sections, especially on mobile devices.
Synchronizing the animations with the user's scroll or interaction events.
Managing and optimizing the use of JavaScript for triggering animations without overloading the DOM or affecting the user experience.
Additional Context: I am using  JavaScript for triggering animations and CSS for handling most of the styling and transition effects. I'm looking for suggestions on improving scroll-based animations and any best practices to follow for maintaining performance.

**Comment by akhileshverma92** [comment]
let's do it🚀

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
