### ISSUE TITLE
[Enhancement] - To add "UPI" option in "Payment Method" list

### ISSUE THREAD

**Issue by AveshShaikh0408** [anuragverma108/WildGuard#961]
We can add "UPI" option in "Payment Method" list. Currently only following options are available.
@anuragverma108, I would like to start contributing this site with simple options as part of Hacktoberfest.

**Screenshot -** 
![EBD307F5-CEFB-49FF-94FD-F24534BDC255](https://github.com/user-attachments/assets/8253cdcf-b73a-497f-89c3-04e24fc0f5ee)

Please assign me this issue if you think this can be a small enhancement to start.

**Comment by Malay207** [comment]
Hi @anuragverma108,  I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

**Comment by AveshShaikh0408** [comment]
> Hi @anuragverma108, I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

PR for this issue is already raise, do check other issues.

**Comment by AveshShaikh0408** [comment]
PR is in review state.
