### ISSUE TITLE
Change the mission, vision and plan field data 

### ISSUE THREAD

**Issue by manisha069** [anuragverma108/WildGuard#97]
![image](https://github.com/user-attachments/assets/7c04bb86-7945-405b-a82d-92e640c2b210)

Currently the Mission/Vision/Plan buttons do not have correct functionality added to them, where clicking on the respective button should change the data below according to the button selected.

Please assign me this issue, my proposed solution is to implement the following:
1. change of data based on the field selected out of Mission, Vision or plan.
2. change the active state (green highlight) of currently displayed tab while others are greyed.

**Comment by manisha069** [comment]
Hi @anuragverma108 can you please assign me this issue?

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!

**Comment by manisha069** [comment]
Thank you, will be sending a PR soon :)
