### ISSUE TITLE
Center Align the contents in the footer 

### ISSUE THREAD

**Issue by AjayAchugatla** [anuragverma108/WildGuard#977]
When viewing web page in the mobile the contents in the footer are not centrally aligned. 

![Screenshot 2024-10-13 130152](https://github.com/user-attachments/assets/4a850248-32b8-4e09-a1bc-89117d939cf4)

**Comment by IbraheemHaseeb7** [comment]
@AjayAchugatla is this self assigned or open?

**Comment by AjayAchugatla** [comment]
self align
