### ISSUE TITLE
Name input not restricted to alphabets only

### ISSUE THREAD

**Issue by KANIKASHARMA0906** [anuragverma108/WildGuard#978]
In the Donate Section Form :
To improve data validation and ensure users input valid names, the name field should be restricted to only allow alphabetic characters (A-Z, a-z) and spaces, preventing the entry of numbers and special symbols.

**Comment by SparshMadaan** [comment]
SparshMadaan:improve-form-validation-error-message

**Comment by SparshMadaan** [comment]
[SparshMadaan:improve-form-validation-error-message](url)

**Comment by SparshMadaan** [comment]
[](SparshMadaan:improve-form-validation-error-message)

**Comment by SparshMadaan** [comment]
#996
