### ISSUE TITLE
Navbar Items not visible if scrolled down. (color problem)

### ISSUE THREAD

**Issue by papireddy903** [anuragverma108/WildGuard#981]
![image](https://github.com/user-attachments/assets/c837693a-52bd-4206-b391-f2bf0cf4be98)
after scrolling down, it shows like this
![image](https://github.com/user-attachments/assets/b04f4c30-c618-45c4-8cb3-e2ebcf667e06)

I would like to work on this issue.

**Comment by kanhaiyadav** [comment]
Hey there, please assign me to this issue i would like to work on it.
