### ISSUE TITLE
Navigation Buttons needs to be highlighted for the user to know which page they're currently browsing

### ISSUE THREAD

**Issue by Shub95-arch** [anuragverma108/WildGuard#99]
Highlighting buttons helps users easily navigate the site and know which page they're on.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in WildGuard! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

Don't forget to follow @anuragverma108 – Project Admin & @PriyaGhosal -Project Collaborator  – for more updates!

We're excited to see your contribution as part of Hacktoberfest 2024! 🎉  
Happy open-source contributing!
